# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      # 1. 自动检测处理 Git 子模块
      - uses: actions/checkout@v4

      # 2. 安装 Flutter
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: dev
      - run: flutter --version
      - run: dart --version
        
      # 3. 安装 Go
      - name: Install Go
        uses: actions/setup-go@v5.5.0
      - run: go version

      - name: Run release
        run: dart setup.dart linux --arch amd64
