# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      # 1. 更新 Git 子模块
      - name: Update submodules
        run: git submodule update --init --recursive

      # 2. 安装 Flutter
      - name: Install Flutter
        uses: geowatson/flutter-latest@1.0.1
          

      # 3. 安装 Go
      - name: Install Go
        uses: actions/setup-go@v5.5.0

      # 验证环境
      - name: Verify installations
        run: |
          flutter --version
          go version

      - name: Run release
        run: dart .\setup.dart linux --arch amd64
