# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      # 1. 检查子模块
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      # 2. 安装 Flutter
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter --version
      - run: dart --version
        
      # 3. 安装 Go
      - name: Install Go
        uses: actions/setup-go@v5.5.0
      - run: go version

      - run: dart pub get
      - run: dart setup.dart linux --arch amd64

      # 创建Release并上传dist目录下的所有文件
      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref }}
          files: dist/**/*
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
